version: "3.9"

services:
  auth-service:
    build: ./auth-backend
    env_file:
      - ./auth-backend/.env
    container_name: auth-service
    ports:
      - "3001:3000"   # localhost:3001 -> container:3000
    networks:
      - app-network

  product-service:
    build: ./product-backend
    container_name: product-service
    env_file:
      - ./product-backend/.env
    ports:
      - "4001:4000"   # localhost:4001 -> container:4000
    networks:
      - app-network

  frontend:
    build: ./frontend/my-app
    container_name: frontend
    expose:
      - "80"
    networks:
      - app-network

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - auth-service
      - product-service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge