version: "3.9"

services:
  frontend:
    build: ./frontend/my-app
    container_name: frontend
    networks:
      - app-network

  auth-backend:
    build: ./auth-backend
    container_name: auth-backend
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb+srv://dineshverse21_db_user:vlMnJsQ6TrWtHnoa@cluster0.ebfy0t8.mongodb.net/?appName=Cluster0
      - JWT_SECRET=mySuperSecretKey123
    ports:
      - "3001:3000"
    networks:
      - app-network

  product-backend:
    build: ./product-backend
    container_name: product-backend
    environment:
      - PORT=4000
      - MONGODB_URI=mongodb+srv://dineshverse21_db_user:vlMnJsQ6TrWtHnoa@cluster0.ebfy0t8.mongodb.net/?appName=Cluster0
      - JWT_SECRET=mySuperSecretKey123
    ports:
      - "4001:4000"
    networks:
      - app-network

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "50:80"
    depends_on:
      - frontend
      - auth-backend
      - product-backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge