server {
    listen 80;

    # React frontend
    location / {
        proxy_pass http://frontend:80;
    }

    # Auth backend
    location /api/auth/ {
        proxy_pass http://auth-service:3001;
    }

    # Product backend
    location /api/products/ {
        proxy_pass http://product-service:4001;
    }
}